// Generates wire-format (snake_case) TypeScript types from OpenRouter's public OpenAPI spec.
// Same source the official @openrouter/sdk is generated from, but types only: zero runtime code.
//
//   npm run gen:types
import { writeFile } from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';

const SPEC_URL = 'https://openrouter.ai/openapi.json';
const OUT = new URL('../src/generated/openrouter-api.d.ts', import.meta.url);

const res = await fetch(SPEC_URL);
if (!res.ok) { throw new Error(`Fetching ${SPEC_URL} failed: ${res.status}`); }
const spec = await res.json();

// The spec contains Speakeasy vendor extensions inside discriminator mappings
// (e.g. "x-speakeasy-unknown-values"), which are not valid $refs. Strip them.
let stripped = 0;
(function clean(node) {
	if (!node || typeof node !== 'object') { return; }
	if (node.discriminator?.mapping) {
		for (const k of Object.keys(node.discriminator.mapping)) {
			if (k.startsWith('x-')) { delete node.discriminator.mapping[k]; stripped++; }
		}
	}
	for (const v of Object.values(node)) { clean(v); }
})(spec);

const ast = await openapiTS(spec, { alphabetize: true });
// The spec's own examples contain full-length sk-or-v1-... strings, which trip
// GitHub push protection. Redact them in the generated output.
const output = astToString(ast).replace(/sk-or-v1-[0-9a-f]{64}/g, 'sk-or-v1-REDACTED');
const header = `/* eslint-disable */
// AUTO-GENERATED by scripts/gen-types.mjs from ${SPEC_URL}
// OpenAPI version: ${spec.info?.version ?? 'unknown'} (fetched ${new Date().toISOString().slice(0, 10)})
// Do not edit by hand. Run \`npm run gen:types\` to update.

`;
await writeFile(OUT, header + output);
console.log(`Wrote ${OUT.pathname} (stripped ${stripped} vendor mapping keys)`);
